In [ ]:
# 본인의 이름, 학번을 작성하여 실행하세요.
print("LKHAGVA MUNKH ERDENE")
print("20242047")

In [1]:
#예제--1--
symbols = "$*&!@"
codes = []

for symbol in symbols:
    codes.append(ord(symbol))

print(codes)

[36, 42, 38, 33, 64]


In [2]:
#예제--2--
symbols = "$*&!@"
codes = [ord(symbol) for symbol in symbols]

print(codes)

[36, 42, 38, 33, 64]


In [3]:
#예제--3--
x= '"!~$$*&!@'
dummy = [ord(x) for x in x]

print (x)
print (dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [4]:
#예제--4--
symbols = '"!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]

print (beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [6]:
#예제--5--
symbols = '"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c>64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f"Map function: \n>>> {map(ord, symbols) }")
print(f"List after map: \n>>> {list (map(ord, symbols) )}")

[126] 

Map function: 
>>> <map object at 0x7c70ae90b730>
List after map: 
>>> [34, 33, 126, 36, 36, 42, 38, 33, 64]


In [9]:
#예제--6--
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]

print (tshirts)

for color in colors:
  for size in sizes:
    print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [10]:
#예제--7--
symbols ="!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord (s))

print (ord_s)

(33, 35, 94, 38, 38, 35)


In [14]:
#예제--8--
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirt in ('{} {}'.format(c, s) for s in sizes for c in colors):
  print(tshirt)

black S
white S
black M
white M
black L
white L


In [15]:
#예제--9--

lax_coordinates = (33.9425, -118.408056)

city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)

traveler_ids = [ ('USA', '31195855'),
                 ('BRA', 'CE342567'),
                 ('ESP', 'XDA205856' ) ]



for passport in sorted (traveler_ids):
  print('%s/%s' % passport)
  print('{}/{}'. format (passport [0], passport [1]))
  print(f'{passport [0]}/{passport [1]}')

BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855


In [16]:
#예제--10--
lax_coordinates = (33.9425, -118.408056)

city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)

traveler_ids = [ ('USA', '31195855'),
                 ('BRA', 'CE342567'),
                 ('ESP', 'XDA205856' ) ]
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


In [17]:
#예제--11--
lax_coordinates = (33.9425, -118.408056)
latitude, longtitude = lax_coordinates
print(latitude)
print(longtitude)

33.9425
-118.408056


In [22]:
#예제--12--
a = 10 ; b = 20
b , a = a , b
print(a , b)

20 10


In [26]:
#예제--13--
divmod(20,8)

t = (20,8)
divmod(*t)

quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [27]:
#예제--14--
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename


'idrsa.pub'

In [28]:
#예제--15--
a, b, *rest = range (5)
a, b, rest

a, b, *rest = range (3)
a, b, rest

a, b, *rest = range (2)
a, b, rest


(0, 1, [])

In [29]:
#예제--16--
a, *body, c, d = range (5)
a, body, c, d

*head, b, c, d = range (5)
head, b, c, d


([0, 1], 2, 3, 4)

In [32]:
#예제--17--
metro_areas = [
    ("Tokyo", "JP", 36.933, (35, 139)),
    ("Delhi NCR", "IN", 21, (28, 77)),
    ("Mexico City", "MX", 20, (19, -99)),
    ("New York-Newark", "US", 20, (40, -74)),
    ("Sao Paulo", "BR", 19, (-23, -46))
]

print("{:15} | {:^9} | {:^9}".format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'

for name, cc, pop, (lat, longi) in metro_areas:
    if longi <= 0:
        print(fmt.format(name, lat, longi))

                |   lat.    |   long.  
Mexico City     |   19.0000 |  -99.0000
New York-Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


In [33]:
#예제--18--
from collections import namedtuple

City = namedtuple('City', 'name country population coordinates')

tokyo = City('Tokyo', 'JP', 36.933, (35.689, 139.691))

print(tokyo)
print(tokyo.population)
print(tokyo.coordinates)
print(tokyo[1])


City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689, 139.691))
36.933
(35.689, 139.691)
JP


In [39]:
#예제--19--
from collections import namedtuple
City._fields
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208))

delhi = City._make(delhi_data)

print(delhi._asdict())

for key, value in delhi._asdict().items():
    print(key + ":", value)

{'name': 'Delhi NCR', 'country': 'IN', 'population': 21.935, 'coordinates': LatLong(lat=28.613, long=77.208)}
name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


In [47]:
#예제--20--
l = [10, 20, 30, 40, 50, 60]
print(l [:2])
print(l [2:])
print(l [:3])
print(l [3:])

[10, 20]
[30, 40, 50, 60]
[10, 20, 30]
[40, 50, 60]


In [44]:
#예제--21--
invoice = '''
0.....6...............25.........33....40....
1909 Pimoroni PiBrella      $17.50   3   $52.50
1489 6mm Tactile Switch     $4.95    2   $9.90
'''

SKU = slice(0, 6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
    if item.strip():
        print(item[UNIT_PRICE], item[DESCRIPTION])

   $17.5 imoroni PiBrella   
   $4.95 mm Tactile Switch  


In [49]:
#예제--22--
l = list (range (10))
print(l)

l [2:5] = [20, 30]
print(l)

del l[5:7]
print(l)

l [3::2] = [11, 22]
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 8, 9]
[0, 1, 20, 11, 5, 22, 9]


In [50]:
#예제--23--
l[2:5] = 100

TypeError: must assign iterable to extended slice

In [51]:
#예제--24--
l[2:5] = [100]
print(l)

[0, 1, 100, 22, 9]


In [55]:
#예제--25--
l = [1,2,3]

print(l *  5)
print(5 * 'abcd')

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
abcdabcdabcdabcdabcd


In [56]:
#예제--26--
board = [['_'] * 3 for i in range (3)]
print(board)
board [1][2] = 'X'
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]


In [57]:
#예제--27--
weird_board = [['_'] * 3] * 3
print(weird_board)

weird_board [1][2] = '0'
print(weird_board)


[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]


In [59]:
#예제--28--
row = ['_'] * 3
board = []
for i in range(3):
  board.append (row)

board [1] [2] = 'X'

board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [61]:
#예제--29--
board = []
for i in range (3):
  row = ['_'] * 3
  board.append (row)
print (board)

board [2] [0] = 'X'

board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [82]:
#예제--30--
l = [1,2,3]
print(id(l))

l *= 2
print(l)

print(id(l))

136823117203776
[1, 2, 3, 1, 2, 3]
136823117203776


In [84]:
#예제--31--
t = (1, 2, 3)
print(id(t))

t *= 2
print(t)

print(id(t))

136823120665600
(1, 2, 3, 1, 2, 3)
136823120700192


In [85]:
#예제--32--
t = (1, 2, [30, 40])
print(t)

t[2] += [50, 60]

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [86]:
#예제--33--
t = (1, 2, [30, 40])
print(t)

(1, 2, [30, 40])


In [88]:
#예제--34--
fruits = ['grape', 'raspberry', 'apple', 'banana']
print(sorted (fruits))

print(fruits)

print(sorted (fruits, reverse=True))

print(sorted (fruits, key=len))


['apple', 'banana', 'grape', 'raspberry']
['grape', 'raspberry', 'apple', 'banana']
['raspberry', 'grape', 'banana', 'apple']
['grape', 'apple', 'banana', 'raspberry']


In [90]:
#예제--35--
fruits = ['grape', 'raspberry', 'apple', 'banana']
print(sorted (fruits, key=len, reverse=True))

print(fruits)

fruits.sort()
print(fruits)

['raspberry', 'banana', 'grape', 'apple']
['grape', 'raspberry', 'apple', 'banana']
['apple', 'banana', 'grape', 'raspberry']


In [94]:
#예제--36--
from array import array
from random import random

floats = array('d', (random() for _ in range(10**7)))
floats[-1]


0.5961519419771353

In [95]:
#예제--37--
from array import array

from random import random
floats = array('d', (random() for i in range(10**7)))

with open('floats.bin', 'wb') as f:
    floats.tofile(f)

floats2 = array('d')

with open('floats.bin', 'rb') as f:
    floats2.fromfile(f, 10**7)

print(floats2[-1])

print(floats == floats2)

0.19614489375128663
True


In [96]:
#예제--38--
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)

print(len(memv))
print(memv[0])

memv_oct = memv.cast('B')
print(memv_oct.tolist())

memv_oct[5] = 4
print(numbers)


5
-2
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
array('h', [-2, -1, 1024, 1, 2])


In [103]:
#예제--38.1--
data = bytearray(b'hello world')
mv = memoryview(data)
print(mv[0])
mv[0] = 72

print(data)

104
bytearray(b'Hello world')


In [105]:
#예제--39--
import numpy
a = numpy.arange (12)
print(a)

type (a)


[ 0  1  2  3  4  5  6  7  8  9 10 11]


numpy.ndarray

In [111]:
#예제--40--
a.shape

a.shape = 3,4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
#예제--41--
import numpy as np

a = np.arange(12).reshape(3, 4)

print(a[2])
print(a[2, 1])
print(a[:, 1])


[ 8  9 10 11]
9
[1 5 9]


In [131]:
#예제--42--
import numpy as np

a = np.arange(12).reshape(3, 4)
b = a.transpose()
print(b)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
